--------------------------------------------------------
-- Archivo creado  - viernes-diciembre-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AFICION
--------------------------------------------------------
create user footbal identified by footbal;

grant connect to footbal;
grant all privileges to footbal identified by footbal;



  CREATE TABLE "FOOTBAL"."AFICION" 
   (	"AFICION_ID" NUMBER, 
	"NOMBRE_GUERRA" VARCHAR2(50 BYTE), 
	"EQUIPO_F" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "FOOTBAL"."AFICION"."AFICION_ID" IS 'la clave de aficion';
--------------------------------------------------------
--  DDL for Table CANTICOS
--------------------------------------------------------

  CREATE TABLE "FOOTBAL"."CANTICOS" 
   (	"CANTICOS_ID" NUMBER, 
	"CANCION" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"AFICION_FK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPO
--------------------------------------------------------

  CREATE TABLE "FOOTBAL"."EQUIPO" 
   (	"EQUIPO_ID" NUMBER, 
	"NOMBRE_IQ" VARCHAR2(40 BYTE), 
	"FECHA_DE_FONDACION" VARCHAR2(20 BYTE), 
	"ESTADIO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "FOOTBAL"."EQUIPO"."EQUIPO_ID" IS 'la clave primaria';
   COMMENT ON COLUMN "FOOTBAL"."EQUIPO"."NOMBRE_IQ" IS 'el nombre del equipo';
--------------------------------------------------------
--  DDL for Table ESTADIO
--------------------------------------------------------

  CREATE TABLE "FOOTBAL"."ESTADIO" 
   (	"ESTADIO_ID" NUMBER, 
	"DIRECCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JUGADOR
--------------------------------------------------------

  CREATE TABLE "FOOTBAL"."JUGADOR" 
   (	"JUGADOR_ID" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APPELLIDO" VARCHAR2(30 BYTE), 
	"DNI" VARCHAR2(20 BYTE), 
	"EQUIPO_FK" NUMBER, 
	"SALARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PELEGROSOS
--------------------------------------------------------

  CREATE TABLE "FOOTBAL"."PELEGROSOS" 
   (	"PELEGROSO_ID" NUMBER, 
	"NOMBRE_PEL" VARCHAR2(20 BYTE), 
	"DNI" VARCHAR2(20 BYTE), 
	"FECHA_NACEMIENTO" DATE, 
	"AFICION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FOOTBAL.AFICION
SET DEFINE OFF;
Insert into FOOTBAL.AFICION (AFICION_ID,NOMBRE_GUERRA,EQUIPO_F) values ('1','COCO',null);
Insert into FOOTBAL.AFICION (AFICION_ID,NOMBRE_GUERRA,EQUIPO_F) values ('2','LILA',null);
Insert into FOOTBAL.AFICION (AFICION_ID,NOMBRE_GUERRA,EQUIPO_F) values ('3','NINA',null);
REM INSERTING into FOOTBAL.CANTICOS
SET DEFINE OFF;
REM INSERTING into FOOTBAL.EQUIPO
SET DEFINE OFF;
Insert into FOOTBAL.EQUIPO (EQUIPO_ID,NOMBRE_IQ,FECHA_DE_FONDACION,ESTADIO_ID) values ('1','REAL MADRID','1902','1');
Insert into FOOTBAL.EQUIPO (EQUIPO_ID,NOMBRE_IQ,FECHA_DE_FONDACION,ESTADIO_ID) values ('2','BARCELONA','1999','2');
Insert into FOOTBAL.EQUIPO (EQUIPO_ID,NOMBRE_IQ,FECHA_DE_FONDACION,ESTADIO_ID) values ('3','VALENCIA','2000','3');
REM INSERTING into FOOTBAL.ESTADIO
SET DEFINE OFF;
Insert into FOOTBAL.ESTADIO (ESTADIO_ID,DIRECCION) values ('1','MADRID');
Insert into FOOTBAL.ESTADIO (ESTADIO_ID,DIRECCION) values ('2','BARAJAS');
Insert into FOOTBAL.ESTADIO (ESTADIO_ID,DIRECCION) values ('3','CCARTAGENA');
REM INSERTING into FOOTBAL.JUGADOR
SET DEFINE OFF;
Insert into FOOTBAL.JUGADOR (JUGADOR_ID,NOMBRE,APPELLIDO,DNI,EQUIPO_FK,SALARIO) values ('1','MESSI','GARCIAS','X21547','1',null);
Insert into FOOTBAL.JUGADOR (JUGADOR_ID,NOMBRE,APPELLIDO,DNI,EQUIPO_FK,SALARIO) values ('2','MANUEL','BAZERA','I21548','2',null);
Insert into FOOTBAL.JUGADOR (JUGADOR_ID,NOMBRE,APPELLIDO,DNI,EQUIPO_FK,SALARIO) values ('3','JUAN','HERMOSO','U5487','3',null);
REM INSERTING into FOOTBAL.PELEGROSOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index AFICION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOOTBAL"."AFICION_PK" ON "FOOTBAL"."AFICION" ("AFICION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CANTICOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOOTBAL"."CANTICOS_PK" ON "FOOTBAL"."CANTICOS" ("CANTICOS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOOTBAL"."EQUIPO_PK" ON "FOOTBAL"."EQUIPO" ("EQUIPO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ESTADIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOOTBAL"."ESTADIO_PK" ON "FOOTBAL"."ESTADIO" ("ESTADIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index JUGADOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOOTBAL"."JUGADOR_PK" ON "FOOTBAL"."JUGADOR" ("JUGADOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PELEGROSOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOOTBAL"."PELEGROSOS_PK" ON "FOOTBAL"."PELEGROSOS" ("PELEGROSO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AFICION
--------------------------------------------------------

  ALTER TABLE "FOOTBAL"."AFICION" MODIFY ("AFICION_ID" NOT NULL ENABLE);
  ALTER TABLE "FOOTBAL"."AFICION" MODIFY ("NOMBRE_GUERRA" NOT NULL ENABLE);
  ALTER TABLE "FOOTBAL"."AFICION" ADD CONSTRAINT "AFICION_PK" PRIMARY KEY ("AFICION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CANTICOS
--------------------------------------------------------

  ALTER TABLE "FOOTBAL"."CANTICOS" MODIFY ("CANTICOS_ID" NOT NULL ENABLE);
  ALTER TABLE "FOOTBAL"."CANTICOS" ADD CONSTRAINT "CANTICOS_PK" PRIMARY KEY ("CANTICOS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOOTBAL"."CANTICOS" MODIFY ("AFICION_FK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPO
--------------------------------------------------------

  ALTER TABLE "FOOTBAL"."EQUIPO" MODIFY ("EQUIPO_ID" NOT NULL ENABLE);
  ALTER TABLE "FOOTBAL"."EQUIPO" MODIFY ("NOMBRE_IQ" NOT NULL ENABLE);
  ALTER TABLE "FOOTBAL"."EQUIPO" ADD CONSTRAINT "EQUIPO_PK" PRIMARY KEY ("EQUIPO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADIO
--------------------------------------------------------

  ALTER TABLE "FOOTBAL"."ESTADIO" MODIFY ("ESTADIO_ID" NOT NULL ENABLE);
  ALTER TABLE "FOOTBAL"."ESTADIO" ADD CONSTRAINT "ESTADIO_PK" PRIMARY KEY ("ESTADIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JUGADOR
--------------------------------------------------------

  ALTER TABLE "FOOTBAL"."JUGADOR" MODIFY ("JUGADOR_ID" NOT NULL ENABLE);
  ALTER TABLE "FOOTBAL"."JUGADOR" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "FOOTBAL"."JUGADOR" MODIFY ("APPELLIDO" NOT NULL ENABLE);
  ALTER TABLE "FOOTBAL"."JUGADOR" MODIFY ("DNI" NOT NULL ENABLE);
  ALTER TABLE "FOOTBAL"."JUGADOR" ADD CONSTRAINT "JUGADOR_PK" PRIMARY KEY ("JUGADOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PELEGROSOS
--------------------------------------------------------

  ALTER TABLE "FOOTBAL"."PELEGROSOS" MODIFY ("PELEGROSO_ID" NOT NULL ENABLE);
  ALTER TABLE "FOOTBAL"."PELEGROSOS" MODIFY ("NOMBRE_PEL" NOT NULL ENABLE);
  ALTER TABLE "FOOTBAL"."PELEGROSOS" MODIFY ("DNI" NOT NULL ENABLE);
  ALTER TABLE "FOOTBAL"."PELEGROSOS" MODIFY ("FECHA_NACEMIENTO" NOT NULL ENABLE);
  ALTER TABLE "FOOTBAL"."PELEGROSOS" ADD CONSTRAINT "PELEGROSOS_PK" PRIMARY KEY ("PELEGROSO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOOTBAL"."PELEGROSOS" MODIFY ("AFICION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AFICION
--------------------------------------------------------

  ALTER TABLE "FOOTBAL"."AFICION" ADD CONSTRAINT "EQUIPO_FK3" FOREIGN KEY ("EQUIPO_F")
	  REFERENCES "FOOTBAL"."EQUIPO" ("EQUIPO_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CANTICOS
--------------------------------------------------------

  ALTER TABLE "FOOTBAL"."CANTICOS" ADD CONSTRAINT "AFICION_FK1" FOREIGN KEY ("AFICION_FK")
	  REFERENCES "FOOTBAL"."AFICION" ("AFICION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPO
--------------------------------------------------------

  ALTER TABLE "FOOTBAL"."EQUIPO" ADD CONSTRAINT "ESTADIO_FK2" FOREIGN KEY ("ESTADIO_ID")
	  REFERENCES "FOOTBAL"."ESTADIO" ("ESTADIO_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JUGADOR
--------------------------------------------------------

  ALTER TABLE "FOOTBAL"."JUGADOR" ADD CONSTRAINT "EQUIPO_FK2" FOREIGN KEY ("EQUIPO_FK")
	  REFERENCES "FOOTBAL"."EQUIPO" ("EQUIPO_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PELEGROSOS
--------------------------------------------------------

  ALTER TABLE "FOOTBAL"."PELEGROSOS" ADD CONSTRAINT "PELEGROSOS_FK1" FOREIGN KEY ("AFICION_ID")
	  REFERENCES "FOOTBAL"."AFICION" ("AFICION_ID") ON DELETE CASCADE ENABLE;
