--es un trigger que hace la insertacion en la tabla salary cuando se modifia un salary de algun employee

CREATE OR REPLACE TRIGGER SALARIO_SUBIDO BEFORE UPDATE 
OF SALARY ON EMPLOYEES 

FOR EACH ROW
			BEGIN
				INSERT INTO  SALARY
				(EMPLOYEE_ID, SALARY_A, SALARY_N, FECHA)
				VALUES (:NEW.EMPLOYEE_ID,:OLD.SALARY,:NEW.SALARY, sysdate);
			END ;
    
				

     --   insert into SALARY(SALARY_ID,EMPLOYEE_ID,SALARY_A,SALARY_N,FECHA) values ('3','100','100','120','10/10/2012');
      
--TRIGGER PARA IMPRIMIR ALGO CUANDO INSERTAR O ACTUALIZAR EL SALARIO 

CREATE OR REPLACE TRIGGER tigre_1_empleados
AFTER INSERT OR UPDATE OF salary ON employees
FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE ('Salario ' ||:NEW.salary); --ES PARA IMPRIMIR EN LA PANTALLA COMO SYSOUT
END;


SET SERVEROUTPUT ON; -- PARA IMPRIMIR EN LA VENTANA

UPDATE EMPLOYEES SET SALARY = SALARY + (SALARY*0.2) WHERE DEPARTMENT_ID = :dpto;
DBMS_OUTPUT.PUT_LINE ('Salario 1' ||:OLD.salary);
DBMS_OUTPUT.PUT_LINE ('Salario 2' ||:NEW.salary);